title: KOALA SAMPLER DOCUMENTATION
author: Nikolai Sokolov
  layout: Alex Oleksandrov
  coding: Stas Pyshevski
  url: https://metawork.studio
  email: hello@metawork.studio


# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Koala is a versatile sampler, sequencer and mixer. 
  Perform your songs with 16 live FX. Create your signature sound with 24 channel effects. 
  STEM SPLIT and TIMESTRETCH among other powerful features. 
  Available for iOS and Android devices, as well as Mac and Windows.

# Build settings

plugins:
  - jekyll-seo-tag

# Theme-specific settings

minima:
# Minima date format.
# Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
#
# date_format: "%b %-d, %Y"

# Generate social links in footer.
#
# social_links:
#   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
#   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
#   - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
#   - { platform: telegram,       user_url: "https://t.me/jekyll" }
#   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }


collections:
  documentation:
    output: false
  #    permalink: /:collection/:path/

  mobile:
    output: true
  #    permalink: /:collection/:path/
  tablet:
    output: true
#    permalink: /:collection/:path/

permalinks: pretty
